# LTS with ghc-8.2.2
resolver: lts-10.3

# LTS with ghc-8.0.2
# resolver: lts-9.1
# resolver: lts-7.19

# Local packages, usually specified by relative directory name
packages:
- '.'
- './catalog-servant'
# - './catalog-server'
# - './catalog-sync'

# - '../../monad-reader-state-err-io'

# Packages to be pulled from upstream that are not in the resolver
extra-deps:
- string-qq-0.0.2
- git: https://github.com/UweSchmidt/monad-reader-state-err-io.git
  commit: abbf19aac8159a646a6c58f850250287c3e2049d

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
system-ghc: false
